import React, { useEffect, useRef, useState } from 'react';
import { useLocation, useNavigate } from 'react-router';
import { useStrategyStore } from '../../../stores/useStrategyStore';
import { usePlannerStore, type SlotLifecycleStatus } from '../../../stores/usePlannerStore';
import {
  Sparkles,
  Copy,
  Check,
  Lightbulb,
  Target,
  Brain,
  Loader2,
  Calendar,
  Download,
  CheckCircle2,
  X,
} from 'lucide-react';
import { PageHeader } from '../../../components/ui/PageHeader';
import { Card } from '../../../components/ui/Card';
import { Button } from '../../../components/ui/Button';
import { Input } from '../../../components/ui/Input';
import { Alert } from '../../../components/ui/Alert';
import { sanitizeStrategyTopic, type StrategyBrief } from '../../../lib/strategyTopic';

const getDefaultScheduledAt = (): string => {
  const tomorrow = new Date();
  tomorrow.setDate(tomorrow.getDate() + 1);
  tomorrow.setHours(10, 0, 0, 0);
  const year = tomorrow.getFullYear();
  const month = String(tomorrow.getMonth() + 1).padStart(2, '0');
  const day = String(tomorrow.getDate()).padStart(2, '0');
  const hours = String(tomorrow.getHours()).padStart(2, '0');
  const minutes = String(tomorrow.getMinutes()).padStart(2, '0');
  return `${year}-${month}-${day}T${hours}:${minutes}`;
};

const buildNotesFromBrief = (brief: StrategyBrief): string => {
  const sections: string[] = [];
  if (brief.script_outline?.hook) {
    sections.push(`Hook:\n${brief.script_outline.hook}`);
  }
  if (brief.script_outline?.retention_mid) {
    sections.push(`Key Points & Retention:\n${brief.script_outline.retention_mid}`);
  }
  if (brief.script_outline?.cta) {
    sections.push(`CTA:\n${brief.script_outline.cta}`);
  }
  if (brief.tags && brief.tags.length > 0) {
    const formattedTags = brief.tags.map((t) => (t.startsWith('#') ? t : `#${t}`)).join(' ');
    sections.push(`SEO Tags:\n${formattedTags}`);
  }
  if (brief.strategy_insight) {
    sections.push(`Strategy Insight:\n${brief.strategy_insight}`);
  }
  return sections.join('\n\n');
};

const buildScriptOutlineMarkdown = (brief: StrategyBrief): string => {
  return `# Script Outline: ${brief.topic}

## Hook
${brief.script_outline?.hook || 'N/A'}

## Key Points & Retention
${brief.script_outline?.retention_mid || 'N/A'}

## Call to Action (CTA)
${brief.script_outline?.cta || 'N/A'}

---
Generated by CreatorIQ Strategy Suite
`;
};

const triggerDownload = (content: string, filename: string, mimeType: string) => {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

const sanitizeFilename = (name: string, suffix: string, ext: string): string => {
  const clean = name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
  return `${clean || 'strategy'}-${suffix}.${ext}`;
};

export const StrategyPage: React.FC = () => {
  const location = useLocation();
  const navigate = useNavigate();
  const [topic, setTopic] = useState('');
  const [goal, setGoal] = useState('Max engagement');
  const [copiedTitleIndex, setCopiedTitleIndex] = useState<number | null>(null);
  const [copiedOutline, setCopiedOutline] = useState(false);
  const [copiedTags, setCopiedTags] = useState(false);

  // Schedule Modal State
  const [isScheduleModalOpen, setIsScheduleModalOpen] = useState(false);
  const [scheduleTopic, setScheduleTopic] = useState('');
  const [scheduleDate, setScheduleDate] = useState(getDefaultScheduledAt());
  const [scheduleStatus, setScheduleStatus] = useState<SlotLifecycleStatus>('not_started');
  const [scheduleNotes, setScheduleNotes] = useState('');
  const [isScheduling, setIsScheduling] = useState(false);
  const [scheduleSuccess, setScheduleSuccess] = useState(false);

  const { brief, sessionId, isLoading, error, generateBrief } = useStrategyStore();
  const handledNavState = useRef(false);

  useEffect(() => {
    const state = location.state as { topic?: string; autoGenerate?: boolean } | null;
    if (!state?.topic || handledNavState.current) return;

    handledNavState.current = true;
    const nextTopic = state.topic.trim();
    setTopic(nextTopic);
    if (state.autoGenerate && nextTopic) {
      void generateBrief(nextTopic, goal);
    }
    navigate(location.pathname, { replace: true, state: null });
  }, [location.state, location.pathname, navigate, generateBrief, goal]);

  const handleCopyTitle = (text: string, index: number) => {
    navigator.clipboard.writeText(text);
    setCopiedTitleIndex(index);
    setTimeout(() => setCopiedTitleIndex(null), 2000);
  };

  const handleCopyOutline = () => {
    if (!brief) return;
    navigator.clipboard.writeText(buildScriptOutlineMarkdown(brief));
    setCopiedOutline(true);
    setTimeout(() => setCopiedOutline(false), 2000);
  };

  const handleExportOutline = () => {
    if (!brief) return;
    const markdown = buildScriptOutlineMarkdown(brief);
    const filename = sanitizeFilename(brief.topic, 'outline', 'md');
    triggerDownload(markdown, filename, 'text/markdown;charset=utf-8');
  };

  const handleCopyTags = () => {
    if (!brief) return;
    const tagsText = (brief.tags ?? []).join(', ');
    navigator.clipboard.writeText(tagsText);
    setCopiedTags(true);
    setTimeout(() => setCopiedTags(false), 2000);
  };

  const handleExportTags = () => {
    if (!brief) return;
    const tagsText = (brief.tags ?? []).join(', ');
    const filename = sanitizeFilename(brief.topic, 'tags', 'txt');
    triggerDownload(tagsText, filename, 'text/plain;charset=utf-8');
  };

  const handleOpenScheduleModal = () => {
    if (!brief) return;
    setScheduleTopic(brief.titles?.[0]?.text || brief.topic);
    setScheduleDate(getDefaultScheduledAt());
    setScheduleStatus('not_started');
    setScheduleNotes(buildNotesFromBrief(brief));
    setIsScheduleModalOpen(true);
  };

  const handleScheduleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!scheduleTopic.trim()) return;

    setIsScheduling(true);
    try {
      const isoDate = new Date(scheduleDate).toISOString();
      await usePlannerStore.getState().createSlot({
        topic: scheduleTopic.trim(),
        scheduled_at: isoDate,
        status: scheduleStatus,
        strategy_session_id: sessionId || undefined,
        notes: scheduleNotes.trim(),
      });
      setIsScheduleModalOpen(false);
      setScheduleSuccess(true);
    } catch (err) {
      console.error('Failed to create planner slot:', err);
    } finally {
      setIsScheduling(false);
    }
  };

  return (
    <div className="space-y-6 pb-6 animate-in">
      <PageHeader
        title={<span className="text-gradient-brand">Strategy</span>}
        description="Generate a data-backed content brief grounded in your channel profile."
      />

      {error && <Alert variant="error">{error}</Alert>}

      {scheduleSuccess && (
        <div className="flex items-center justify-between gap-3 rounded-lg border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800 animate-in fade-in">
          <div className="flex items-center gap-2">
            <CheckCircle2 className="h-5 w-5 text-emerald-600 shrink-0" />
            <div>
              <p className="font-semibold">Slot scheduled in Content Planner!</p>
              <p className="text-xs text-emerald-700 mt-0.5">
                Your video slot has been added to the calendar linked to this strategy session.
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <Button
              size="sm"
              onClick={() => navigate('/app/planner')}
              className="bg-emerald-600 hover:bg-emerald-700 text-white shadow-xs text-xs"
            >
              <Calendar className="mr-1.5 h-3.5 w-3.5" />
              Open Planner
            </Button>
            <button
              type="button"
              onClick={() => setScheduleSuccess(false)}
              className="p-1 text-emerald-600 hover:text-emerald-900 rounded-md hover:bg-emerald-100"
              title="Dismiss"
            >
              <X className="h-4 w-4" />
            </button>
          </div>
        </div>
      )}

      <div className="grid grid-cols-1 gap-6 lg:grid-cols-12">
        <div className="space-y-4 lg:col-span-4">
          <Card variant="elevated" className="space-y-4">
            <div>
              <label className="text-xs font-medium text-neutral-500">Target topic</label>
              <div className="mt-1.5">
                <Input
                  icon={<Lightbulb className="h-4 w-4" />}
                  value={topic}
                  onChange={(e) => setTopic(e.target.value)}
                  placeholder="e.g. comedy shorts trends"
                />
              </div>
            </div>
            <div>
              <label className="text-xs font-medium text-neutral-500">Primary goal</label>
              <div className="relative mt-1.5">
                <Target className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-neutral-400" />
                <select
                  value={goal}
                  onChange={(e) => setGoal(e.target.value)}
                  className="h-9 w-full appearance-none rounded-lg border border-neutral-200 bg-white pl-9 pr-3 text-sm focus:border-brand-600 focus:outline-none focus:ring-2 focus:ring-brand-600/10"
                >
                  <option value="Max engagement">Max engagement</option>
                  <option value="Audience growth">Audience growth</option>
                  <option value="Monetization focus">Monetization focus</option>
                </select>
              </div>
            </div>
            <Button
              className="w-full"
              onClick={() => {
                const cleaned = sanitizeStrategyTopic(topic);
                if (cleaned) void generateBrief(cleaned, goal);
              }}
              disabled={isLoading || !sanitizeStrategyTopic(topic)}
            >
              {isLoading ? 'Generating...' : 'Generate strategy'}
            </Button>
          </Card>

          <Card variant="dark">
            <Sparkles className="h-4 w-4 text-brand-300" />
            <h3 className="mt-3 text-sm font-medium">AI advantage</h3>
            <p className="mt-2 text-sm text-neutral-400">
              Strategies use your real niche data and channel context via OpenRouter.
            </p>
          </Card>
        </div>

        <div className="lg:col-span-8">
          {!brief ? (
            <Card variant="elevated" className="flex min-h-[320px] flex-col items-center justify-center border-dashed border-brand-200/50 text-center">
              <div className="mb-4 flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br from-brand-100 to-brand-50 ring-1 ring-brand-200/50 text-brand-600">
                <Brain className="h-6 w-6" />
              </div>
              <h3 className="text-base font-medium text-neutral-900">
                {isLoading ? 'Generating your strategy...' : 'Waiting for input'}
              </h3>
              <p className="mt-2 max-w-xs text-sm text-neutral-500">
                {isLoading
                  ? 'AI is building titles, hooks, and a script outline for your topic.'
                  : 'Enter a topic to generate a data-backed content strategy.'}
              </p>
              {isLoading && <Loader2 className="mt-4 h-6 w-6 animate-spin text-brand-600" />}
            </Card>
          ) : (
            <Card variant="elevated" className="space-y-8">
              <section className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 border-b border-neutral-100 pb-5">
                <div>
                  <div className="flex items-center gap-2">
                    <p className="text-xs font-medium text-brand-600">Growth strategy</p>
                    {sessionId && (
                      <span className="inline-flex items-center rounded-full bg-purple-50 px-2 py-0.5 text-[10px] font-medium text-purple-700 ring-1 ring-inset ring-purple-600/20">
                        Session: {sessionId.slice(0, 8)}
                      </span>
                    )}
                  </div>
                  <h2 className="mt-1 text-xl font-semibold text-neutral-900">{brief.topic}</h2>
                </div>
                <Button
                  variant="primary"
                  onClick={handleOpenScheduleModal}
                  className="shrink-0 shadow-sm"
                >
                  <Calendar className="mr-2 h-4 w-4" />
                  Schedule to Planner
                </Button>
              </section>

              <section>
                <p className="rounded-lg border border-brand-100 bg-brand-50 p-4 text-sm text-brand-900">
                  <Sparkles className="mb-1 inline h-4 w-4 text-brand-600" /> {brief.strategy_insight}
                </p>
              </section>

              <section>
                <h3 className="text-sm font-medium text-neutral-900">Optimized titles</h3>
                <div className="mt-3 space-y-2">
                  {(brief.titles ?? []).map((t, i) => (
                    <div
                      key={i}
                      className="flex items-center justify-between gap-3 rounded-lg border border-neutral-200 bg-neutral-50 px-3 py-2.5"
                    >
                      <div>
                        <p className="text-sm font-medium text-neutral-800">{t.text}</p>
                        <p className="text-xs text-neutral-500">{t.hook_type || 'Custom hook'}</p>
                      </div>
                      <button
                        type="button"
                        onClick={() => handleCopyTitle(t.text, i)}
                        className="rounded p-1.5 text-neutral-400 hover:bg-white hover:text-brand-600"
                        title="Copy title"
                      >
                        {copiedTitleIndex === i ? <Check className="h-4 w-4 text-emerald-600" /> : <Copy className="h-4 w-4" />}
                      </button>
                    </div>
                  ))}
                </div>
              </section>

              <section>
                <div className="flex items-center justify-between mb-3">
                  <h3 className="text-sm font-medium text-neutral-900">Script outline</h3>
                  <div className="flex items-center gap-2">
                    <Button
                      type="button"
                      variant="secondary"
                      size="sm"
                      onClick={handleCopyOutline}
                      className="h-8 px-2.5 text-xs"
                      title="Copy structured script outline to clipboard"
                    >
                      {copiedOutline ? (
                        <>
                          <Check className="mr-1.5 h-3.5 w-3.5 text-emerald-600" />
                          Copied!
                        </>
                      ) : (
                        <>
                          <Copy className="mr-1.5 h-3.5 w-3.5" />
                          Copy Outline
                        </>
                      )}
                    </Button>
                    <Button
                      type="button"
                      variant="secondary"
                      size="sm"
                      onClick={handleExportOutline}
                      className="h-8 px-2.5 text-xs"
                      title="Download script outline as Markdown"
                    >
                      <Download className="mr-1.5 h-3.5 w-3.5" />
                      Export Markdown
                    </Button>
                  </div>
                </div>
                <div className="space-y-3">
                  <div className="rounded-lg bg-neutral-900 p-4 text-white">
                    <p className="text-xs text-brand-400">Hook</p>
                    <p className="mt-2 text-sm">{brief.script_outline?.hook}</p>
                  </div>
                  <div className="rounded-lg border border-neutral-200 p-4">
                    <p className="text-xs text-neutral-500">Retention</p>
                    <p className="mt-2 text-sm text-neutral-800">{brief.script_outline?.retention_mid}</p>
                  </div>
                  <div className="rounded-lg bg-brand-600 p-4 text-white">
                    <p className="text-xs text-white/70">CTA</p>
                    <p className="mt-2 text-sm">{brief.script_outline?.cta}</p>
                  </div>
                </div>
              </section>

              <section>
                <div className="flex items-center justify-between mb-3">
                  <h3 className="text-sm font-medium text-neutral-900">SEO tags</h3>
                  <div className="flex items-center gap-2">
                    <Button
                      type="button"
                      variant="secondary"
                      size="sm"
                      onClick={handleCopyTags}
                      className="h-8 px-2.5 text-xs"
                      title="Copy SEO tags to clipboard"
                    >
                      {copiedTags ? (
                        <>
                          <Check className="mr-1.5 h-3.5 w-3.5 text-emerald-600" />
                          Copied!
                        </>
                      ) : (
                        <>
                          <Copy className="mr-1.5 h-3.5 w-3.5" />
                          Copy Tags
                        </>
                      )}
                    </Button>
                    <Button
                      type="button"
                      variant="secondary"
                      size="sm"
                      onClick={handleExportTags}
                      className="h-8 px-2.5 text-xs"
                      title="Download SEO tags as text file"
                    >
                      <Download className="mr-1.5 h-3.5 w-3.5" />
                      Export TXT
                    </Button>
                  </div>
                </div>
                <div className="flex flex-wrap gap-2">
                  {(brief.tags ?? []).map((tag, i) => (
                    <span
                      key={i}
                      className="rounded-md border border-neutral-200 bg-neutral-50 px-2 py-1 text-xs text-neutral-600"
                    >
                      #{tag}
                    </span>
                  ))}
                </div>
              </section>
            </Card>
          )}
        </div>
      </div>

      {/* Schedule to Planner Modal */}
      {isScheduleModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4 backdrop-blur-xs animate-in fade-in">
          <div
            className="w-full max-w-lg rounded-xl bg-white p-6 shadow-2xl border border-neutral-200 animate-in zoom-in-95"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="flex items-center justify-between pb-3 border-b border-neutral-100">
              <div className="flex items-center gap-2">
                <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-brand-50 text-brand-600">
                  <Calendar className="h-4 w-4" />
                </div>
                <div>
                  <h3 className="text-base font-semibold text-neutral-900">Schedule to Planner</h3>
                  <p className="text-xs text-neutral-500">Plan this brief directly on your content calendar</p>
                </div>
              </div>
              <button
                type="button"
                onClick={() => setIsScheduleModalOpen(false)}
                className="p-1 text-neutral-400 hover:text-neutral-700 rounded-md hover:bg-neutral-100"
              >
                <X className="h-4 w-4" />
              </button>
            </div>

            {sessionId && (
              <div className="mt-3 flex items-center gap-1.5 rounded-md bg-purple-50 px-2.5 py-1 text-xs text-purple-700 border border-purple-200">
                <span className="font-semibold">Strategy Session:</span>
                <span className="font-mono">{sessionId.slice(0, 8)}...</span>
                <span className="text-purple-500 text-[11px]">(automatically linked)</span>
              </div>
            )}

            <form onSubmit={handleScheduleSubmit} className="mt-4 space-y-4">
              <div>
                <label className="block text-xs font-medium text-neutral-700 mb-1">
                  Video Title / Topic *
                </label>
                <Input
                  value={scheduleTopic}
                  onChange={(e) => setScheduleTopic(e.target.value)}
                  placeholder="e.g. 5 AI Tools Every Creator Needs"
                  required
                />
                {brief?.titles && brief.titles.length > 1 && (
                  <div className="mt-1.5 flex flex-wrap items-center gap-1.5">
                    <span className="text-[11px] text-neutral-400 mr-1">Choose title:</span>
                    {brief.titles.map((t, idx) => (
                      <button
                        key={idx}
                        type="button"
                        onClick={() => setScheduleTopic(t.text)}
                        className="rounded bg-neutral-100 px-2 py-0.5 text-[11px] text-neutral-600 hover:bg-brand-50 hover:text-brand-700 transition-colors"
                      >
                        {t.text.length > 35 ? t.text.slice(0, 35) + '...' : t.text}
                      </button>
                    ))}
                  </div>
                )}
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs font-medium text-neutral-700 mb-1">
                    Target Date & Time *
                  </label>
                  <input
                    type="datetime-local"
                    value={scheduleDate}
                    onChange={(e) => setScheduleDate(e.target.value)}
                    required
                    className="h-9 w-full rounded-lg border border-neutral-200 bg-white px-2.5 text-xs text-neutral-900 focus:border-brand-600 focus:outline-none focus:ring-2 focus:ring-brand-600/10"
                  />
                </div>

                <div>
                  <label className="block text-xs font-medium text-neutral-700 mb-1">
                    Initial Status
                  </label>
                  <select
                    value={scheduleStatus}
                    onChange={(e) => setScheduleStatus(e.target.value as SlotLifecycleStatus)}
                    className="h-9 w-full rounded-lg border border-neutral-200 bg-white px-2.5 text-xs text-neutral-900 focus:border-brand-600 focus:outline-none focus:ring-2 focus:ring-brand-600/10"
                  >
                    <option value="not_started">Not Started</option>
                    <option value="scripting">Scripting</option>
                    <option value="recording">Recording</option>
                    <option value="editing">Editing</option>
                    <option value="ready">Ready to Publish</option>
                  </select>
                </div>
              </div>

              <div>
                <label className="block text-xs font-medium text-neutral-700 mb-1">
                  Notes / Outline Summary
                </label>
                <textarea
                  rows={4}
                  value={scheduleNotes}
                  onChange={(e) => setScheduleNotes(e.target.value)}
                  className="w-full rounded-lg border border-neutral-200 bg-white p-2.5 text-xs text-neutral-900 placeholder:text-neutral-400 focus:border-brand-600 focus:outline-none focus:ring-2 focus:ring-brand-600/10"
                />
              </div>

              <div className="flex items-center justify-end gap-2 pt-3 border-t border-neutral-100">
                <Button
                  type="button"
                  variant="secondary"
                  size="sm"
                  onClick={() => setIsScheduleModalOpen(false)}
                >
                  Cancel
                </Button>
                <Button type="submit" size="sm" disabled={isScheduling || !scheduleTopic.trim()}>
                  {isScheduling ? (
                    <>
                      <Loader2 className="h-3.5 w-3.5 animate-spin mr-1.5" />
                      Scheduling...
                    </>
                  ) : (
                    <>
                      <Calendar className="h-3.5 w-3.5 mr-1.5" />
                      Schedule Slot
                    </>
                  )}
                </Button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};
