[alembic]
script_location = migrations
version_table = alembic_version_planner

sqlalchemy.url = ${DATABASE_URL}

[loggers]
keys = root,sqlalchemy,alembic
levels = INFO
handlers = console
qualname = alembic

[handlers]
keys = console
class = StreamHandler
args = (sys.stderr,)
level = INFO
formatter = generic

[formatters]
keys = generic
class = %(class)s
format = %(message)s

