[backend]
ciq ansible_host=172.198.162.160 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/ciq_key.pem

[backend:vars]
ansible_python_interpreter=/usr/bin/python3
domain_name=api.ciq.yashparmar.in
app_dir=/opt/creatoriq/backend
secrets_dir=/opt/creatoriq/secrets
